config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :chat_rooms
  root to: "chat_rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  has_many :chat_rooms, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for resource
    stored_location_for(resource) || chat_rooms_path
  end

  def after_sign_out_path_for resource
    stored_location_for(resource) || new_user_session_path
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController

  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_room = ChatRoom.find_by id: params[:id]
  end
  
  def new
    @chat_room = ChatRoom.new
  end
  
  def create
    @chat_room = current_user.chat_rooms.build chat_room_params
    if @chat_room.save
      flash[:success] = "Chat room created"
      redirect_to chat_rooms_path
    else
      render :new
    end
  end

  private
  def chat_room_params
    params.require(:chat_room).permit :title
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li>
  <%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %>
</li>

app/views/chat_rooms/_chat_room.js.erb
$(document).ready(function(){
  App.room = App.cable.subscriptions.create({channel: "ChatRoomsChannel",
    chat_room_id: <%= @chat_room.id %>}, {
    received: function(data) {
      data_display = display_message(data);
      $("#messages").append(data_display);
    }
  });

  $("#submit").click(function(){
    message = $(".messages-send")[0];
    if($(message).val().length > 0){
      var date = new Date();
      App.room.send({message: $(message).val(), time_stamp: date.toLocaleString(),
        chat_room_id: <%= @chat_room.id %>});
      $(message).val("");
    }
  });

  function display_message(data){
    var content = "<div class='col-lg-6'>" + data["user"] + ":" + data["message"] + "</div>";
    var time_stamp = "<div class='col-lg-6 text-right'>" + data["time_stamp"] + "</div>";
    return "<div class='row'>" + content + time_stamp + "</div>";
  }
});

app/views/chat_rooms/index.html.erb
<div class="offset-lg-3 col-lg-6">
  <div>This is list chat room</div>
  <h1>Chat rooms</h1>

  <p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

  <%= render @chat_rooms %>
</div>

app/views/chat_rooms/new.html.erb
<div class="offset-lg-3 col-lg-6">
  <h1>Add chat room</h1>

  <%= form_for @chat_room do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
      </div>

      <%= f.submit "Add!", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <%= link_to "List Rooms", chat_rooms_path, class: "btn btn-primary" %>
    </div>
    <div class="col-lg-6">This is chat room <%= @chat_room.title %></div>
  </div>
  <div class="row">
    <div class="messages-box col-lg-12" id="messages">
    </div>
  </div>
  <div class="row">
    <textarea class="messages-send col-lg-12" rows="4">
    </textarea>

    <div class="text-right col-lg-12">
      <button class="btn btn-primary" id="submit">Enter</button>
    </div>
  </div>

  <%= content_for :specific_page_js do %>
    <script type="text/javascript">
        <%= render "chat_room.js" %>
    </script>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="text-center" style="margin-bottom: 50px;">
  <h1>CableChat</h1>
</div>
<div style="padding-right: 50px;">
  <% if user_signed_in? %>
    <div class="text-right">
      User: <%= current_user.email %>
    </div>
    <div class="text-right">
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CableChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= render partial: "/layouts/header" %>
  </header>
  <body>
    <%= yield %>
  </body>

  <%= javascript_include_tag 'application'%>
  <%= content_for :specific_page_js %>
</html>